DEFINE_ACTION_FUNCTION candlekeep
BEGIN
  // Restore doppleganger Erik

  LAUNCH_PACTION_FUNCTION install
    STR_VAR
    file	= "erik3.d"
    location	= "dialogs"
  END

  LAUNCH_ACTION_FUNCTION edit_area
    STR_VAR
    area	= "%Candlekeep_Catacombs_L2%"
    editstring	= %add_actor_inline'01=>~actor_name=>"{literal:Doppleganger Erik}" actor_resource=>"erik3" actor_x_coord=>1430 actor_y_coord=>260 actor_orientation=>14~%	// NB: % signs are string delimiters here!
  END
END	// candlekeep


