DEFINE_ACTION_FUNCTION summon_restorations_preproc
BEGIN
  // Install updated tables

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "monsum01 monsum04 monsum03 monsum04 monsum05 monsum06 monsum07"
    postfix	= "2da"
    location	= "tables"
  END


  // Reclaim partial description strings

  ACTION_IF NOT GAME_IS "bgee"
  BEGIN
    STRING_SET 16165 @1 16170 @3 16358 @5 16359 @7
  END
END	// summon_restorations_preproc


