DEFINE_ACTION_FUNCTION banter_bg2
BEGIN
  LAUNCH_ACTION_FUNCTION extend
    STR_VAR
    script	= "minsc"
    bottom	= "minsc_banter_bg2"
    location	= "resources"
  END

  LAUNCH_ACTION_FUNCTION extend
    STR_VAR
    script	= "yoshimo"
    bottom	= "yoshimo_banter_bg2"
    location	= "resources"
  END

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "banter_bg2.d"
    location	= "resources"
  END
END	// banter_bg2


