DEFINE_ACTION_FUNCTION spell_restorations_preproc
BEGIN
  // spwi801 was dummied out, but the icons were re-used for spwi519
  // (Spell Shield).  Rename them so we can re-use spwi801 safely.

  COPY_EXISTING "spwi801a.bam" "override/spwi519a.bam"
                "spwi801b.bam" "override/spwi519b.bam"
                "spwi801c.bam" "override/spwi519c.bam"

  spl.edit[spwi519]
  [
    m_icon:="spwi519c"
    m.ab.alter{s_icon:="spwi519b"}
  ]

  itm.edit[scrl8x]
  [
    m_icon:="spwi519a"
    m.ab.alter{s_icon:="spwi519a"}
  ]


  // Reclaim partial description strings

  ACTION_IF NOT GAME_IS "bgee"
  BEGIN
    STRING_SET 25870 @20 26324 @3 34643 @16 25950 @22 26296 @5 25868 @18 38565 @7 12183 @27 35556 @28 2575 @30
  END


  // Reserve new spell ids for spell that have changed level.

  LAUNCH_ACTION_FUNCTION spl_resolve_ids
    INT_VAR
    level		= 6
    replace_on_mismatch	= 1
    STR_VAR
    ids			= "WIZARD_TATTOOS_OF_POWER"
    type		= "wizard"
  END

  LAUNCH_ACTION_FUNCTION spl_resolve_ids
    INT_VAR
    level		= 2
    replace_on_mismatch	= 1
    STR_VAR
    ids			= "CLERIC_CURE_BLIND_DEAF"
    type		= "priest"
  END


  // Preclaim ids for spells with known spell ids. (Due to found icons.)

  APPEND "spell.ids" "2706    WIZARD_MONSTER_SUMMONING_5"	UNLESS "^2706"
  APPEND "spell.ids" "2801    WIZARD_MONSTER_SUMMONING_6"	UNLESS "^2706"
  APPEND "spell.ids" "2901    WIZARD_SPELL_INVULNERABILITY"	UNLESS "^2901"
  APPEND "spell.ids" "2904    WIZARD_MONSTER_SUMMONING_7"	UNLESS "^2706"
  APPEND "spell.ids" "2906    WIZARD_SANDFORM"			UNLESS "^2906"

  LAM data_spell_resrefs
END	// spell_restorations_preproc


