DEFINE_ACTION_FUNCTION setup_bg2_encounters
BEGIN
  LAUNCH_ACTION_FUNCTION get_directory
    STR_VAR
    location
    locbase
    locabs
    RET
    directory
  END

  ACTION_BASH_FOR "%directory%" "^bg2_.*\.tpa"
  BEGIN
    ACTION_TO_LOWER BASH_FOR_RES

    LAUNCH_ACTION_FUNCTION run
      STR_VAR
      file	= "%BASH_FOR_RES%"
      tra	= "%BASH_FOR_RES%"
    END
  END
END	// setup_bg2_encounters


