DEFINE_ACTION_FUNCTION bg1_baldurs_gate_stores
BEGIN
  // tem0149 - Shrine of Ilmater

  LAUNCH_ACTION_FUNCTION edit_store
    STR_VAR
    store	= "tem0149"
    editstring	= "name_string=>15031"
  END


  // tem0609 - Water Queen's House

  LAUNCH_ACTION_FUNCTION edit_store
    STR_VAR
    store	= "tem0609"
    editstring	= "name_string=>14977 rumors=>rbaldu rumors_donation=>rbaldu"
  END


END	// bg1_baldurs_gate_stores


